version: '3.8'

services:
  db:
    container_name: consulticom-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'consulticom-db'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'postgres'

  backend:
    container_name: nestjs_project
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:1234@db/consulticom-db
  
  frontend:
    container_name: react_vite_app
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - backend

networks:
  default:
    driver: bridge