version: '3.8'

services:
  db:
    container_name: consulticom-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'consulticom-db'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'postgres'
    networks:
      default:
        aliases:
          - postgres.service
  node:
    container_name: nestjs_project
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
